#!/bin/bash

set -e

here=$(dirname $(realpath "$0" 2> /dev/null || grealpath "$0"))
. "$here"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

pkgname="libevent"
info "Building $pkgname..."

pushd "$here"
git clone  https://github.com/libevent/libevent.git

pushd "$here"/$pkgname || fail "Could not chdir to $here/$pkgname"
git checkout 4c908dde58ef780eeefcc9df4db3063ca62ea862
if ! [ -x configure ] ; then
    ./autogen.sh || fail "Could not configure $pkgname"
fi
if ! [ -r config.status ] ; then
    ./configure \
        $AUTOCONF_FLAGS \
        --prefix="$here/$pkgname/dist" \
        --disable-shared \
        --enable-static \
        --with-pic \
        --disable-samples \
        --disable-libevent-regress \
        CPPFLAGS=-I"$here"/openssl/dist \
        LDFLAGS=-L"$here"/openssl/dist || fail "Could not configure $pkgname"
fi
make -j$WORKER_COUNT || fail "Could not build $pkgname"
make install || fail "Could not install $pkgname"
popd
popd
