#!/bin/bash

contrib=$(dirname "$0")
test -n "$contrib" -a -d "$contrib" || (echo "Could not find the contrib/ directory" && exit 1)
pushd "$contrib"
contrib=`pwd`  # abs path name

. "$contrib"/base.sh || (echo "Could not source contrib/base.sh" && exit 1)

set -e

pushd "$contrib"/..

TAGGED_VERSION=`git describe --tags` || fail "Could not get determine git tag version"

info "Making SrcDist for version: ${PACKAGE}-${TAGGED_VERSION} ..."

"$contrib"/make_locale && \
    "$contrib"/make_packages && \
    python3 setup.py sdist --enable-secp --enable-zbar --format=zip,gztar || fail "Failed."

unset TAGGED_VERSION

info "Linux source distribution (including compiled libseck256k1 & libzbar) has been placed in dist/"

popd
popd
