common: &COMMON_TEMPLATE
  timeout_in: 120m
  clone_script: |
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  env:
    GIT_REPO: $CIRRUS_WORKING_DIR

task:
  name: "Build MacOS DMG"
  << : *COMMON_TEMPLATE
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  brew_script:
    - brew update
    - brew install coreutils gettext pyenv
  test_script:
    - cd contrib/osx && ./make_osx
  binaries_artifacts:
    path: "dist/*.dmg"
  trigger_type: manual

docker_builder:
  name: "Build Linux AppImage"
  << : *COMMON_TEMPLATE
  platform: linux
  build_script:
    - contrib/build-linux/appimage/build.sh $CIRRUS_BRANCH
  binaries_artifacts:
    path: "dist/*.AppImage"
  trigger_type: manual

docker_builder:
  name: "Build source distribution"
  << : *COMMON_TEMPLATE
  platform: linux
  build_script:
    - contrib/build-linux/srcdist_docker/build.sh $CIRRUS_BRANCH
  binaries_artifacts:
    path: "dist/*.tar.gz"
  trigger_type: manual

docker_builder:
  name: "Build Windows EXE"
  << : *COMMON_TEMPLATE
  platform: linux
  build_script:
    - contrib/build-wine/build.sh $CIRRUS_BRANCH
  binaries_artifacts:
    path: "dist/*.exe"
  trigger_type: manual

task:
  name: "Tests"
  build_script:
    - pip install -r contrib/requirements/requirements-ci.txt
  test_script:
    - python -m electroncash.tests -v
    - python -m electroncash_plugins.fusion.tests -v
  matrix:
    - container:
        image: python:3.7
    - container:
        image: python:3.8
    - container:
        image: python:3.9
    - container:
        image: python:3.10
    - container:
        image: python:3.11
    - windows_container:
        image: "python:3.11-windowsservercore"


task:
  name: "Tests (secp256k1)"
  build_script:
    - set -e
    - contrib/make_secp
    - pip install -r contrib/requirements/requirements-ci.txt
  test_script:
    - set -e
    - coverage run -m electroncash.tests -v;
    - coverage run -m electroncash_plugins.fusion.tests -v;
    # FIXME: coverage report no longer works on cirrus.
    # - coverage report --include="./electroncash*";
  matrix:
    - container:
        image: python:3.11
